### ISSUE TITLE
Allow customization of nested configuration of the sbt-assembly plugin

### ISSUE THREAD

**Issue by agemooij** [typesafehub/sbt-multi-jvm#22]
While upgrading to a newer version of a dependency, we ran in to the problem that the multijvm plugin uses the sbt-assembly plugin to produce a test jar and that assembly plugin throws an error dealing with merging files.

This is the error we got:

    [error] (rebb-multijvm-test/multi-jvm:assembly) deduplicate: different file contents found in the following:
    [error] /Users/age/.ivy2/cache/io.netty/netty/bundles/netty-3.8.0.Final.jar:META-INF/maven/io.netty/netty/pom.properties
    [error] /Users/age/.ivy2/cache/com.datastax.cassandra/cassandra-driver-core/bundles/cassandra-driver-core-2.1.4.jar:META-INF/maven/io.netty/netty/pom.properties
    [error] (rebb-shopper/multi-jvm:assembly) deduplicate: different file contents found in the following:
    [error] /Users/age/.ivy2/cache/com.datastax.cassandra/cassandra-driver-core/bundles/cassandra-driver-core-2.1.4.jar:META-INF/maven/io.netty/netty/pom.properties
    [error] /Users/age/.ivy2/cache/io.netty/netty/bundles/netty-3.8.0.Final.jar:META-INF/maven/io.netty/netty/pom.properties

The problem is that there is no way to override the merge strategies used internally by the multijvm plugin. The only options we had left was to not use that new version of our dependency or to fork the multijvm plugin.

Nested assembly config should be exposed for customization along with the other multijvm keys so that users can solve these issues.

**Comment by patriknw** [comment]
cc @bantonsson

**Comment by bantonsson** [comment]
I think this would be great. I remember there was some issue with this and plugins using plugins when this code was last touched, but when it gets updated for the latest sbt and sbt-assembly it might be possible to do.

**Comment by msfrank** [comment]
i think that PR #19 will enable this functionality.  the change at https://github.com/msfrank/sbt-multi-jvm/commit/fe862ffa5597dbc852a8cb52151ce620e07dd358#diff-ad54d47177586fbaf474e402dd1b3dc5R137 will pass through the merge strategy defined with settings key (assemblyMergeStrategy in assembly) as long as the file is not one of *.class, *.txt, or NOTICE, which are hardcoded merge strategies.

i *think* this technique should apply to other assembly settings keys.  however i'm still learning how the internals of sbt plugins work :)

**Comment by agemooij** [comment]
Sounds good!
What is the status of #19? Everything seems ready to merge so what is holding back the merge and a potential new release?

**Comment by ktoso** [comment]
We just needed @msfrank to confirm our contributor agreement (easy online 1-click process), since that's in place now I've merged #19 and resolving this issue :)

**Comment by ktoso** [comment]
We may cut a release for these just merged in features, I'll ping github once we do.

**Comment by agemooij** [comment]
Thanks!

**Comment by ktoso** [comment]
agemooij - the promised ping :-) Released 0.3.9, and moved repos - it now lives in  https://github.com/sbt/sbt-multi-jvm

Happy hakking!

**Comment by ktoso** [comment]
@agemooij - the promised ping :-) Released 0.3.9, and moved repos - it now lives in  https://github.com/sbt/sbt-multi-jvm

Happy hakking!

**Comment by agemooij** [comment]
And thanks again ;) I'll try it out ASAP
