### ISSUE TITLE
Allow multiple MultiNodeSpec tests to run in parallel on the same machine

### ISSUE THREAD

**Issue by raboof** [typesafehub/sbt-multi-jvm#24]
sbt-multi-jvm sets some parameters to help akka multi-node-testing (http://doc.akka.io/docs/akka/current/dev/multi-node-testing.html). 

In particular, however, it does not set `multinode.server-port`. This means you cannot have 2 sbt processes running multi-node tests on the same machine, as they'll compete for port 4711.

This is of course especially bad on CI machines.

Could we somehow make this port configurable, to allow for example choosing a random one from a range? Or am I missing something entirely?

**Comment by ktoso** [comment]
We're moving repositories, migrated this issue as well: https://github.com/sbt/sbt-multi-jvm/issues/1
